# Generated by Django 2.1.1 on 2018-10-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=10)),
                ('Apellido', models.CharField(max_length=10)),
                ('Rol', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Resolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumeroResolucion', models.CharField(max_length=20)),
                ('FechaDeAutorizacion', models.DateField()),
                ('Serie', models.CharField(max_length=2)),
                ('NumeroInicial', models.IntegerField()),
                ('NumeroFinal', models.IntegerField()),
                ('TipoDeDocumento', models.CharField(max_length=15)),
            ],
        ),
    ]
