# Generated by Django 2.1.1 on 2018-10-29 01:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Resoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucion',
            name='Operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Resoluciones.Operador'),
        ),
    ]
